name: idp-rag-backend:v1

services:
  backend:
    build:
      # context: ./backend
      dockerfile: Dockerfile
    container_name: idp-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped